service:
  name: github-labels

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  profile: dncrews
  region: us-east-1

functions:
  svg:
    handler: api.handler
    events:
      - http:
          method: get
          path: /{proxy+}
