service:
  name: github-labels

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: api.handler
    events:
      - http:
          method: get
          path: hello
